name: Testing and build workflow

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint
      - name: Lint Python files
        run: |
          python -m pylint --rcfile= .pylintrc $(git ls-files '*.py')

  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Unittests
        run: |
          tox
      - name: Installation
        run: |
          python -m pip install .